import type React from "react";

export const profilePageStyles: { [key: string]: React.CSSProperties } = {
  page: {
    padding: "40px",
    maxWidth: "1200px",
    margin: "0 auto",
    color: "var(--profile-page-text)",
  },
  loading: {
    textAlign: "center",
    marginTop: "100px",
    color: "var(--profile-page-loading)",
  },
  headerContainer: {
    display: "flex",
    alignItems: "flex-start",
    marginBottom: "40px",
    gap: "24px",
  },
  avatarWrapper: {
    width: "120px",
    height: "120px",
    borderRadius: "50%",
    cursor: "pointer",
    overflow: "hidden",
    position: "relative",
    border: "2px solid var(--profile-page-avatar-border)",
    flexShrink: 0,
  },
  avatarImg: { width: "100%", height: "100%", objectFit: "cover" },
  username: {
    margin: "12px 0",
    fontSize: "30px",
  },
  inputWrapper: {
    position: "relative",
    margin: "12px 0",
    borderRadius: "6px",
    border: "1px solid var(--profile-page-input-border)",
    backgroundColor: "var(--profile-page-input-bg)",
  },
  input: {
    padding: "6px",
    color: "var(--profile-page-input-text)",
    background: "transparent",
    outline: "none",
    border: "none",
  },
  checkbox: {
    position: "absolute",
    top: "4px",
    right: "4px",
  },
  saveBtn: {
    border: "none",
    backgroundColor: "transparent",
    textDecorationLine: "underline",
    fontSize: "14px",
    fontFamily: "Fredoka",
    color: "var(--profile-page-save-text)",
    cursor: "pointer",
  },
  publicMeta: {
    margin: "12px 0 0",
    color: "var(--profile-page-empty-text)",
    fontSize: "14px",
  },
  shelvesSection: {
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: "60px",
    marginBottom: "64px",
  },
  shelf: {
    flex: 1,
    minWidth: "300px",
  },
  title: {
    textDecoration: "none",
    fontFamily: "Fredoka",
    color: "var(--profile-page-title)",
  },
  sectionHeader: {
    marginBottom: "24px",
    fontSize: "20px",
    fontFamily: "Fredoka",
  },
  emptyText: { color: "var(--profile-page-empty-text)" },
  progressTrack: {
    width: "100%",
    backgroundColor: "var(--profile-page-progress-track)",
    height: "6px",
    borderRadius: "3px",
    marginTop: "8px",
    overflow: "hidden",
  },
  progressBar: {
    backgroundColor: "var(--profile-page-accent)",
    height: "100%",
    borderRadius: "3px",
  },
  progressText: {
    fontSize: "12px",
    color: "var(--profile-page-empty-text)",
    marginTop: "4px",
    textAlign: "right",
  },
  quoteCard: {
    border: "1px solid var(--profile-page-quote-border)",
    borderRadius: "16px",
    padding: "18px",
    background: "var(--profile-page-quote-bg)",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    maxWidth: "500px",
  },
  quoteMeta: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    alignItems: "flex-end",
    borderTop: "1px solid var(--profile-page-quote-border)",
    paddingTop: "12px",
  },
  quoteText: {
    margin: 0,
    lineHeight: 1.6,
    color: "var(--profile-page-quote-text)",
  },
  quoteDate: {
    letterSpacing: "0.05em",
    color: "var(--profile-page-empty-text)",
    fontSize: "13px",
  },
  quoteSource: {
    color: "var(--profile-page-accent)",
    fontFamily: "Fredoka",
    textDecoration: "none",
    fontSize: "16px",
    fontWeight: 600,
  },
};
